version: "3"

services:
  nodpaybchaind:
    image: eosio/eos:latest
    command: /opt/eosio/bin/nodpaybchaind.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodpaybchaind:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodpaybchaind
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodpaybchain-data-volume:/opt/eosio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kpaybchaind:
    image: eosio/eos:latest
    command: /opt/eosio/bin/kpaybchaind --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kpaybchaind:8900 --http-alias=localhost:8900
    hostname: kpaybchaind
    links:
      - nodpaybchaind
    volumes:
      - kpaybchaind-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m

volumes:
 nodpaybchain-data-volume:
   external: true
 kpaybchaind-data-volume:
   external: true
